### ISSUE TITLE
How to view pseudolabels images?

### ISSUE THREAD

**Issue by rst1991** [cchen-cc/SFDA-DPL#8]
Pseudolabels are saved in .npz format. How to visualize it ?

**Comment by rst1991** [comment]
@cchen-cc Can you please help in generating pseudolabels. I am not able to visualize it.

**Comment by cchen-cc** [comment]
After reading the data from .npz files, you can then plot it out.

**Comment by rst1991** [comment]
@cchen-cc I am able to read data from .npz file but I am not able to plot it. 



import matplotlib.pyplot as plt
import numpy as np
from numpy import load
from torchvision import transforms
from PIL import Image 
import PIL 

data = load('/data3/sfd/SFDA-DPL-main/generate_pseudo/pseudolabel_D2.npz', allow_pickle=True)
lst = data.files
for item in lst:
    print(item)
    print(data[item])
my_array=data[data.files[0]]



dfile = "/data3/sfd/SFDA-DPL-main/generate_pseudo/pseudolabel_D2.npz"
images = np.load(dfile,allow_pickle=True)["arr_0"]
tensor=images
tran = transforms.ToPILImage()
img = tran(tensor)
img.show()


![Screenshot from 2023-01-18 11-30-46](https://user-images.githubusercontent.com/121851596/213096406-0f509dfe-5097-4d52-b26b-561403694e1d.png)

**Comment by cchen-cc** [comment]
You can use plt.imshow() to plot the image.

**Comment by rst1991** [comment]
@cchen-cc 
import matplotlib.pyplot as plt
import numpy as np
from torchvision import transforms
from PIL import Image 
import PIL 

dfile = "/data3/sfd/SFDA-DPL-main/generate_pseudo/pseudolabel_D2.npz"
images = np.load(dfile,allow_pickle=True)["arr_0"]
plt.imshow(images)

Traceback (most recent call last):
  File "readlabel.py", line 51, in <module>
    plt.imshow(images)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2651, in imshow
    None else {}), **kwargs)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5626, in imshow
    im.set_data(X)
  File "/data3/rrd/rrd_py37/lib/python3.7/site-packages/matplotlib/image.py", line 694, in set_data
    "float".format(self._A.dtype))
TypeError: Image data of dtype <U6 cannot be converted to float
